package config

const (
	APP_PORT         = "APP_PORT"
	SOCKET_PORT      = "SOCKET_PORT"
	APP_HOST         = "APP_HOST"
	PYTHON_NODE_PORT = "PYTHON_NODE_PORT"

	DB_HOST     = "DB_HOST"
	DB_PORT     = "DB_PORT"
	DB_NAME     = "DB_NAME"
	DB_USER     = "DB_USER"
	DB_PASSWORD = "DB_PASSWORD"

	REDIS_URL    = "REDIS_URL"
	RABBITMQ_URL = "RABBITMQ_URL"

	SMTP_EMAIL    = "SMTP_EMAIL"
	SMTP_HOST     = "SMTP_HOST"
	SMTP_PORT     = "SMTP_PORT"
	SMTP_PASSWORD = "SMTP_PASSWORD"
)
